GET http://localhost:3000
### 
GET http://localhost:3000/games
###
GET http://localhost:3000/games/1
###
POST http://localhost:3000/games
content-Type:application/json

{
    "name":"super mario",
    "genre":"platformer",
    "price":59.99,
    "releaseDate":"2023-10-20"
}

###
PUT http://localhost:3000/games/1
content-Type:application/json

{
    "name": "street fighter 2 turbo",
    "genre": "fighting",
    "price": 9.99,
    "releaseDate": "1992-07-15"
}

###
DELETE http://localhost:3000/games/1


